"""empty message

Revision ID: 693fd6d9d3c7
Revises: ddce500e79dd
Create Date: 2022-06-14 23:26:31.095278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693fd6d9d3c7'
down_revision = 'ddce500e79dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('horoscope_user_id_fkey', 'horoscope', type_='foreignkey')
    op.create_foreign_key(None, 'horoscope', 'user', ['user_id'], ['user_id'])
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user', 'user_id')
    op.drop_constraint(None, 'horoscope', type_='foreignkey')
    op.create_foreign_key('horoscope_user_id_fkey', 'horoscope', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
